import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";
import { createRemoteJWKSet, jwtVerify } from "https://esm.sh/jose@5.9.6";
import { jsPDF } from "https://esm.sh/jspdf@2.5.2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const JWKS = createRemoteJWKSet(new URL(`${Deno.env.get("SUPABASE_URL")}/auth/v1/.well-known/jwks.json`));

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  try {
    const auth = req.headers.get("Authorization")?.replace("Bearer ", "");
    if (!auth) return new Response("unauthorized", { status: 401, headers: corsHeaders });
    const { payload } = await jwtVerify(auth, JWKS);
    const userId = payload.sub as string;

    const supabase = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);

    const now = new Date();
    const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);
    const monthLabel = monthStart.toLocaleString(undefined, { month: "long", year: "numeric" });

    const [{ data: profile }, { data: events }] = await Promise.all([
      supabase.from("profiles").select("display_name").eq("user_id", userId).maybeSingle(),
      supabase.from("savings_events")
        .select("category, food_name, amount_usd, occurred_at")
        .eq("user_id", userId)
        .gte("occurred_at", monthStart.toISOString()),
    ]);

    const total = (events ?? []).reduce((s, e) => s + Number(e.amount_usd || 0), 0);
    const byCat: Record<string, number> = {};
    const byFood: Record<string, number> = {};
    for (const e of events ?? []) {
      byCat[e.category] = (byCat[e.category] || 0) + Number(e.amount_usd || 0);
      const f = e.food_name || "Other";
      byFood[f] = (byFood[f] || 0) + Number(e.amount_usd || 0);
    }
    const topFoods = Object.entries(byFood).sort((a, b) => b[1] - a[1]).slice(0, 5);

    const doc = new jsPDF({ unit: "pt", format: "letter" });
    doc.setFontSize(22); doc.setTextColor(46, 93, 58);
    doc.text("Saver's Pantry Monthly Recap", 50, 60);
    doc.setFontSize(12); doc.setTextColor(80);
    doc.text(`${profile?.display_name ?? "You"} — ${monthLabel}`, 50, 82);

    doc.setFillColor(245, 240, 225);
    doc.roundedRect(50, 110, 500, 90, 12, 12, "F");
    doc.setFontSize(11); doc.setTextColor(120);
    doc.text("TOTAL SAVED", 70, 140);
    doc.setFontSize(36); doc.setTextColor(46, 93, 58);
    doc.text(`$${total.toFixed(2)}`, 70, 180);
    doc.setFontSize(10); doc.setTextColor(120);
    doc.text(`across ${(events ?? []).length} actions`, 70, 196);

    doc.setFontSize(14); doc.setTextColor(46, 93, 58);
    doc.text("By category", 50, 240);
    doc.setFontSize(11); doc.setTextColor(60);
    let y = 262;
    for (const [k, v] of Object.entries(byCat)) {
      doc.text(`${k.replace("_", " ")}`, 60, y);
      doc.text(`$${v.toFixed(2)}`, 500, y, { align: "right" });
      y += 18;
    }

    y += 20;
    doc.setFontSize(14); doc.setTextColor(46, 93, 58);
    doc.text("Top foods", 50, y); y += 22;
    doc.setFontSize(11); doc.setTextColor(60);
    for (const [name, value] of topFoods) {
      doc.text(name, 60, y);
      doc.text(`$${value.toFixed(2)}`, 500, y, { align: "right" });
      y += 18;
    }

    doc.setFontSize(9); doc.setTextColor(140);
    doc.text("Generated by Saver's Pantry. Keep saving — small swaps add up.", 50, 740);

    const buf = doc.output("arraybuffer");
    return new Response(buf, {
      headers: {
        ...corsHeaders,
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="saverspantry-${monthStart.toISOString().slice(0, 7)}.pdf"`,
      },
    });
  } catch (e: any) {
    return new Response(JSON.stringify({ error: e.message }), { status: 500, headers: corsHeaders });
  }
});
