// Curated top-10 food swaps per cuisine, two angles:
//  - cost: high-cost ingredient → cheaper one with similar nutrition
//  - calorie: high-calorie ingredient → lighter one with similar nutrition
// These are static suggestions for inspiration; users can tap one to run the
// equivalency engine on the original ingredient.
export type SwapPair = { from: string; to: string; note: string };

export const COST_SWAPS: Record<string, SwapPair[]> = {
  American: [
    { from: "Beef sirloin", to: "Ground turkey", note: "Lean protein at ~40% the price" },
    { from: "Salmon fillet", to: "Canned pink salmon", note: "Same omega-3s, half the cost" },
    { from: "Boneless skinless chicken breast", to: "Bone-in thighs", note: "Same protein, ~50% cheaper" },
    { from: "Bacon", to: "Turkey bacon", note: "Less expensive per slice" },
    { from: "Heavy cream", to: "Evaporated milk", note: "Similar richness, fraction of cost" },
    { from: "Cheddar block (premium)", to: "Store-brand cheddar", note: "Same protein and fat" },
    { from: "Maple syrup", to: "Pancake syrup", note: "Way cheaper for pancakes" },
    { from: "Fresh blueberries", to: "Frozen blueberries", note: "Same nutrition, ~60% cheaper" },
    { from: "Pre-cut salad kit", to: "Whole romaine head", note: "Same greens, 1/3 the cost" },
    { from: "Almond flour", to: "Oat flour", note: "Cheaper, similar baking texture" },
  ],
  Pakistani: [
    { from: "Mutton (goat)", to: "Bone-in chicken", note: "Same curry depth, much cheaper" },
    { from: "Beef boti", to: "Beef chuck cubes", note: "Same protein, leaner cut" },
    { from: "Basmati (premium aged)", to: "Standard basmati", note: "Same dish, ~40% cheaper" },
    { from: "Pine nuts (chilgoza)", to: "Toasted cashews", note: "Same crunch, fraction of cost" },
    { from: "Ghee (branded)", to: "Homemade ghee from butter", note: "Same fat, much cheaper" },
    { from: "Saffron", to: "Turmeric + paprika", note: "Color & warmth, near-zero cost" },
    { from: "Paneer (store-bought)", to: "Homemade paneer from milk", note: "Same protein, half the cost" },
    { from: "Whole almonds for kheer", to: "Slivered almonds", note: "Same flavor, less per gram" },
    { from: "Pre-mixed garam masala (branded)", to: "Whole spices ground at home", note: "Fresher, cheaper per use" },
    { from: "Naan from restaurant", to: "Homemade roti", note: "Same carb, pennies per piece" },
  ],
  Indian: [
    { from: "Paneer", to: "Firm tofu", note: "Similar protein, lower cost" },
    { from: "Cashew paste", to: "Soaked sunflower seeds", note: "Creamy gravies, much cheaper" },
    { from: "Ghee", to: "Mustard or sunflower oil", note: "Same browning, lower cost" },
    { from: "Toor dal", to: "Yellow split peas", note: "Same protein and fiber" },
    { from: "Mutton", to: "Chicken thighs", note: "Curry-friendly, far cheaper" },
    { from: "Saffron", to: "Turmeric + paprika", note: "Color match, near-zero cost" },
    { from: "Fresh paneer", to: "Cottage cheese", note: "Similar protein per gram" },
    { from: "Imported basmati", to: "Domestic long-grain rice", note: "Same carb base" },
    { from: "Pomegranate seeds (anar)", to: "Dried pomegranate (anardana)", note: "Same tang, longer shelf life" },
    { from: "Branded curry powder", to: "Homemade spice mix", note: "Cheaper, fresher" },
  ],
  Italian: [
    { from: "Parmigiano-Reggiano", to: "Domestic Parmesan", note: "Similar umami, much cheaper" },
    { from: "Veal", to: "Pork shoulder", note: "Slow-cooks the same, less cost" },
    { from: "Pine nuts (pesto)", to: "Walnuts", note: "Same texture, ~70% cheaper" },
    { from: "Imported San Marzano tomatoes", to: "Quality domestic plum tomatoes", note: "Sauce tastes nearly identical" },
    { from: "Fresh mozzarella di bufala", to: "Low-moisture mozzarella", note: "Cheaper, melts well on pizza" },
    { from: "Prosciutto di Parma", to: "Domestic prosciutto", note: "Same salt-cured profile" },
    { from: "Wild-caught branzino", to: "Tilapia or trout", note: "Mild white fish at lower price" },
    { from: "Truffle oil", to: "Mushroom + olive oil reduction", note: "Earthy aroma for cents" },
    { from: "Imported balsamic", to: "Balsamic + honey reduction", note: "Same sweet-tang for less" },
    { from: "00 flour", to: "All-purpose flour", note: "Works for most pastas/pizza" },
  ],
  Mexican: [
    { from: "Cotija", to: "Feta", note: "Salty crumble, often cheaper" },
    { from: "Carne asada (skirt steak)", to: "Flank steak", note: "Same grill profile, less cost" },
    { from: "Queso Oaxaca", to: "Low-moisture mozzarella", note: "Same melt, cheaper" },
    { from: "Fresh tortillas (pack)", to: "Masa harina + press", note: "Pennies per tortilla" },
    { from: "Dried chipotle peppers", to: "Smoked paprika + chili powder", note: "Smoky depth, much cheaper" },
    { from: "Mexican crema", to: "Sour cream thinned with milk", note: "Same drizzle, lower cost" },
    { from: "Whole black beans (canned)", to: "Dry black beans", note: "1/4 the cost per serving" },
    { from: "Hass avocado (out of season)", to: "Frozen avocado pulp", note: "Same fats, stable price" },
    { from: "Fresh lime juice (bottled brand)", to: "Whole limes", note: "Cheaper per oz" },
    { from: "Pre-made mole paste", to: "Cocoa + chili + nut blend", note: "Homemade for less" },
  ],
  Chinese: [
    { from: "Premium soy sauce", to: "Light soy sauce (regular)", note: "Same salt, less per bottle" },
    { from: "Beef tenderloin (stir-fry)", to: "Beef chuck thinly sliced", note: "Cheaper, tender if sliced thin" },
    { from: "Shrimp (large)", to: "Smaller shrimp", note: "Same flavor, less per pound" },
    { from: "Sesame oil (toasted, premium)", to: "Standard toasted sesame oil", note: "Same aroma" },
    { from: "Shaoxing wine", to: "Dry sherry", note: "Similar depth, often cheaper" },
    { from: "Fresh shiitake", to: "Dried shiitake (rehydrated)", note: "More umami per dollar" },
    { from: "Hoisin (branded)", to: "Plum sauce + soy + 5-spice", note: "DIY for less" },
    { from: "Bok choy (baby)", to: "Regular bok choy", note: "Same vegetable, cheaper" },
    { from: "Black vinegar (Chinkiang premium)", to: "Standard rice vinegar + dark soy", note: "Close flavor, less cost" },
    { from: "Pork belly (premium)", to: "Pork shoulder", note: "Braises similarly" },
  ],
  Mediterranean: [
    { from: "Imported feta", to: "Domestic feta", note: "Same crumble, cheaper" },
    { from: "Lamb chops", to: "Ground lamb or chicken", note: "Same flavor profile, less cost" },
    { from: "Kalamata olives (jarred premium)", to: "Bulk-bin olives", note: "Same olive, less per oz" },
    { from: "Pine nuts", to: "Slivered almonds", note: "Toasty crunch, much cheaper" },
    { from: "Branzino", to: "Tilapia", note: "Mild white fish, lower cost" },
    { from: "Tahini (imported)", to: "Domestic tahini", note: "Same texture" },
    { from: "Saffron", to: "Turmeric + paprika", note: "Color & warmth for less" },
    { from: "Fresh herbs (bunch)", to: "Frozen or dried herbs", note: "Cheaper, longer-lasting" },
    { from: "Halloumi", to: "Firm paneer or queso panela", note: "Same grill behavior" },
    { from: "Pomegranate molasses", to: "Reduced pomegranate juice + sugar", note: "DIY for cents" },
  ],
  Thai: [
    { from: "Thai basil (fresh)", to: "Italian basil + mint", note: "Close aroma, easier to find" },
    { from: "Galangal", to: "Ginger + lime zest", note: "Similar bright heat, cheaper" },
    { from: "Kaffir lime leaves", to: "Lime zest", note: "Same citrus pop, near-zero cost" },
    { from: "Palm sugar", to: "Light brown sugar", note: "Same sweetness profile" },
    { from: "Coconut cream (premium)", to: "Full-fat coconut milk", note: "Stir to thicken, cheaper" },
    { from: "Fresh shrimp", to: "Frozen shrimp", note: "Same nutrition, lower cost" },
    { from: "Massaman curry paste (jar)", to: "Red paste + cumin + cinnamon", note: "DIY massaman for less" },
    { from: "Fish sauce (premium)", to: "Standard fish sauce", note: "Same umami" },
    { from: "Cashews (whole)", to: "Cashew pieces", note: "Same flavor, ~30% cheaper" },
    { from: "Jasmine rice (premium)", to: "Standard jasmine", note: "Same fragrance" },
  ],
};

export const CALORIE_SWAPS: Record<string, SwapPair[]> = {
  American: [
    { from: "Ground beef (80/20)", to: "Ground turkey (93/7)", note: "Same protein, ~30% fewer calories" },
    { from: "Mayonnaise", to: "Plain Greek yogurt", note: "Creamy, way fewer calories" },
    { from: "Sour cream", to: "Plain Greek yogurt", note: "Same tang, less fat" },
    { from: "Bacon", to: "Canadian bacon", note: "Same flavor, far less fat" },
    { from: "Caesar dressing", to: "Yogurt + lemon + anchovy", note: "Lighter, same kick" },
    { from: "French fries", to: "Air-fried potato wedges", note: "Same potato, less oil" },
    { from: "Whole milk", to: "1% milk", note: "Same calcium, fewer cals" },
    { from: "Cream cheese (regular)", to: "Whipped cottage cheese", note: "Spread similarly, more protein" },
    { from: "Buttered popcorn", to: "Air-popped + spray oil", note: "Same volume, way fewer cals" },
    { from: "Ranch dip", to: "Yogurt-ranch", note: "Same flavor base, lighter" },
  ],
  Pakistani: [
    { from: "Ghee (frying)", to: "Olive or canola oil (sprayed)", note: "Same browning, fewer cals" },
    { from: "Full-fat coconut cream in korma", to: "Light coconut milk + cashew", note: "Same body, less fat" },
    { from: "Deep-fried samosa", to: "Baked or air-fried samosa", note: "Same filling, ~50% fewer cals" },
    { from: "White basmati pulao", to: "Brown basmati pulao", note: "Same dish, more fiber, slower carbs" },
    { from: "Mutton qorma", to: "Chicken qorma (skinless)", note: "Same gravy, lighter protein" },
    { from: "Sweetened lassi", to: "Salted lassi", note: "Same drink, fewer sugars" },
    { from: "Naan", to: "Tandoori roti (whole wheat)", note: "Same accompaniment, fewer cals" },
    { from: "Halwa with sugar syrup", to: "Halwa with dates + less ghee", note: "Same sweet, less sugar+fat" },
    { from: "Paratha (layered)", to: "Plain roti with a brush of oil", note: "Far fewer cals per piece" },
    { from: "Fried pakora", to: "Baked pakora", note: "Same chickpea crunch, lighter" },
  ],
  Indian: [
    { from: "Paneer (full-fat)", to: "Tofu (firm)", note: "Same texture, ~40% fewer cals" },
    { from: "Ghee in tadka", to: "Mustard oil (small amount)", note: "Same depth, fewer cals" },
    { from: "White basmati", to: "Brown basmati or millet", note: "More fiber, slower carbs" },
    { from: "Coconut milk in curry", to: "Light coconut milk", note: "Same flavor, less fat" },
    { from: "Cashew gravy base", to: "Sunflower-seed + yogurt", note: "Creamy, lighter" },
    { from: "Deep-fried samosa", to: "Baked samosa", note: "Same filling, less oil" },
    { from: "Sugar in chai", to: "Stevia or less sugar", note: "Same warmth, fewer cals" },
    { from: "Butter chicken (cream-heavy)", to: "Tomato-yogurt makhani", note: "Same dish, lighter" },
    { from: "Malai kofta (fried)", to: "Baked paneer kofta", note: "Same gravy, fewer cals" },
    { from: "Gulab jamun (syrup)", to: "Baked rasgulla", note: "Sweet without deep-fry" },
  ],
  Italian: [
    { from: "Heavy cream alfredo", to: "Cauliflower-cream alfredo", note: "Same silky sauce, far fewer cals" },
    { from: "Pancetta in carbonara", to: "Lean turkey bacon", note: "Same smoke, less fat" },
    { from: "Regular pasta", to: "Whole-wheat or chickpea pasta", note: "More fiber/protein, fewer net carbs" },
    { from: "Mozzarella (full-fat)", to: "Part-skim mozzarella", note: "Same melt, fewer cals" },
    { from: "Ricotta in lasagna", to: "Low-fat ricotta + spinach", note: "Lighter layers" },
    { from: "Olive oil (heavy pour)", to: "Olive oil spray", note: "Same flavor, way fewer cals" },
    { from: "Pesto (oily)", to: "Yogurt-basil pesto", note: "Bright, lower cal" },
    { from: "Pizza dough (white)", to: "Cauliflower or whole-wheat crust", note: "Lighter base" },
    { from: "Tiramisu (mascarpone)", to: "Greek yogurt tiramisu", note: "Same coffee dessert, lighter" },
    { from: "Veal parm (breaded, fried)", to: "Baked chicken parm", note: "Same idea, fewer cals" },
  ],
  Mexican: [
    { from: "Refried beans (lard)", to: "Mashed black beans (no lard)", note: "Same protein, far less fat" },
    { from: "Sour cream", to: "Plain Greek yogurt", note: "Same drizzle, lighter" },
    { from: "Flour tortilla (large)", to: "Corn tortilla", note: "Fewer cals, more fiber" },
    { from: "Chorizo", to: "Lean turkey chorizo", note: "Same spice, lighter fat" },
    { from: "Queso dip (cream-heavy)", to: "Black bean + roasted pepper dip", note: "Lighter, same scoop appeal" },
    { from: "Carnitas (fatty cuts)", to: "Pork loin shredded with broth", note: "Same shred, less fat" },
    { from: "Hard taco shell (fried)", to: "Soft corn tortilla", note: "Same taco, fewer cals" },
    { from: "Mexican rice (oil-fried)", to: "Tomato-cilantro rice (steamed)", note: "Same flavor, less oil" },
    { from: "Margarita (sugary mix)", to: "Tequila + lime + soda", note: "Same kick, way fewer cals" },
    { from: "Churros (fried)", to: "Baked cinnamon-sugar churros", note: "Same flavor, lighter" },
  ],
  Chinese: [
    { from: "Sweet and sour pork (battered, fried)", to: "Stir-fried pork with sweet-sour sauce", note: "Same flavors, far fewer cals" },
    { from: "Fried rice", to: "Steamed rice + veggie stir-fry", note: "Same plate, less oil" },
    { from: "Crispy chow mein", to: "Soft noodles tossed with sauce", note: "Same noodle, less frying oil" },
    { from: "General Tso's chicken (fried + sugary)", to: "Baked chicken with reduced sauce", note: "Same flavors, lighter" },
    { from: "Egg roll (deep-fried)", to: "Spring roll (rice paper)", note: "Same fillings, few cals" },
    { from: "Sesame oil (heavy pour)", to: "Sesame oil drizzle finish", note: "Same aroma, fewer cals" },
    { from: "Pork belly (braised, fatty)", to: "Pork tenderloin braise", note: "Lean cut, same sauce" },
    { from: "Hoisin glaze (sugar)", to: "Hoisin + rice vinegar (less)", note: "Same sticky, less sugar" },
    { from: "Sweetened bubble tea", to: "Cold-brew tea + small tapioca", note: "Same vibe, fewer cals" },
    { from: "White rice (large)", to: "Cauliflower-rice + small white rice", note: "Lighter base" },
  ],
  Mediterranean: [
    { from: "Feta (full-fat)", to: "Light feta", note: "Same crumble, fewer cals" },
    { from: "Hummus (oil-heavy)", to: "Hummus with less tahini + lemon", note: "Same dip, lighter" },
    { from: "Lamb chops", to: "Lean lamb loin or chicken thigh", note: "Same flavor profile, fewer cals" },
    { from: "Pita (white, large)", to: "Whole-wheat pita (small)", note: "Fewer cals, more fiber" },
    { from: "Baklava", to: "Greek yogurt + honey + walnuts", note: "Same flavors, way lighter" },
    { from: "Olive oil (heavy in salad)", to: "Olive oil + lemon + vinegar", note: "Stretch the oil, fewer cals" },
    { from: "Spanakopita (buttery phyllo)", to: "Crustless spinach-feta bake", note: "Same filling, lighter" },
    { from: "Gyro meat (fatty)", to: "Grilled chicken souvlaki", note: "Same wrap idea, leaner" },
    { from: "Tzatziki (full-fat yogurt)", to: "Tzatziki with 2% Greek yogurt", note: "Same sauce, fewer cals" },
    { from: "Falafel (deep-fried)", to: "Baked falafel", note: "Same crunch, less oil" },
  ],
  Thai: [
    { from: "Coconut cream in curry", to: "Light coconut milk", note: "Same body, fewer cals" },
    { from: "Pad Thai (heavy oil + sugar)", to: "Pad Thai with less oil + lime sweetness", note: "Same dish, lighter" },
    { from: "Fried spring rolls", to: "Fresh summer rolls (rice paper)", note: "Same fillings, way fewer cals" },
    { from: "Mango sticky rice (large)", to: "Mango + small portion sticky rice", note: "Same flavors, lighter" },
    { from: "Massaman with potatoes + cream", to: "Massaman with sweet potato + light coconut", note: "Same warmth, fewer cals" },
    { from: "Thai iced tea (sweetened condensed milk)", to: "Cold tea + light milk + a touch of honey", note: "Same color, fewer cals" },
    { from: "Pad See Ew (oily)", to: "Pad See Ew with less oil + extra greens", note: "Same dish, lighter" },
    { from: "Crispy fried fish", to: "Steamed fish with chili-lime", note: "Same protein, fewer cals" },
    { from: "Khao Pad (fried rice)", to: "Steamed jasmine + stir-fry veg", note: "Same plate, less oil" },
    { from: "Satay with peanut sauce (heavy)", to: "Satay with light peanut-yogurt sauce", note: "Same skewer, lighter dip" },
  ],
};
