// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.0";

// src/lib/mcp/tools/list-pantry-items.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_pantry_items_default = defineTool({
  name: "list_pantry_items",
  title: "List pantry items",
  description: "List the signed-in user's pantry items. Optionally filter by storage location (pantry, fridge, freezer, counter) or a search string on the item name.",
  inputSchema: {
    location: z.string().optional().describe("Filter by storage location, e.g. 'pantry', 'fridge', 'freezer', 'counter'."),
    search: z.string().optional().describe("Case-insensitive substring match on the item name."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ location, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser(ctx).from("pantry_items").select("id,item,quantity,unit,location,category,expires_on,updated_at").order("location", { ascending: true }).order("item", { ascending: true }).limit(limit ?? 100);
    if (location) q = q.eq("location", location);
    if (search) q = q.ilike("item", `%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-pantry-item.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var add_pantry_item_default = defineTool2({
  name: "add_pantry_item",
  title: "Add pantry item",
  description: "Add a new item to the signed-in user's pantry. Use location values like 'pantry', 'fridge', 'freezer', or 'counter'.",
  inputSchema: {
    item: z2.string().trim().min(1).describe("Item name, e.g. 'olive oil'."),
    quantity: z2.number().min(0).optional().describe("Quantity (default 1)."),
    unit: z2.string().optional().describe("Unit, e.g. 'ea', 'oz', 'lb', 'g' (default 'ea')."),
    location: z2.string().optional().describe("Storage location (default 'pantry')."),
    category: z2.string().optional().describe("Optional category, e.g. 'produce', 'dairy'."),
    expires_on: z2.string().optional().describe("ISO date (YYYY-MM-DD) for expiration.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("pantry_items").insert({
      user_id: ctx.getUserId(),
      item: input.item,
      quantity: input.quantity ?? 1,
      unit: input.unit ?? "ea",
      location: input.location ?? "pantry",
      category: input.category ?? null,
      expires_on: input.expires_on ?? null
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Added ${data.item} to ${data.location}.` }],
      structuredContent: { item: data }
    };
  }
});

// src/lib/mcp/tools/list-favorite-stores.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.0";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_favorite_stores_default = defineTool3({
  name: "list_favorite_stores",
  title: "List favorite stores",
  description: "Return the signed-in user's favorite grocery stores (up to 3) with name, chain, and city.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    const { data: profile, error: pErr } = await sb.from("profiles").select("favorite_store_ids").eq("user_id", ctx.getUserId()).maybeSingle();
    if (pErr) return { content: [{ type: "text", text: pErr.message }], isError: true };
    const ids = profile?.favorite_store_ids ?? [];
    if (ids.length === 0) {
      return {
        content: [{ type: "text", text: "No favorite stores set yet." }],
        structuredContent: { stores: [] }
      };
    }
    const { data: stores, error: sErr } = await sb.from("specialty_stores").select("id,name,chain,city,region,address").in("id", ids);
    if (sErr) return { content: [{ type: "text", text: sErr.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(stores ?? []) }],
      structuredContent: { stores: stores ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-deals.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_deals_default = defineTool4({
  name: "search_deals",
  title: "Search current deals",
  description: "Search currently active, approved grocery deals. Filter by food name, city, or store name. Returns items on sale right now with price and store info.",
  inputSchema: {
    food: z3.string().optional().describe("Substring match on the food/item name."),
    city: z3.string().optional().describe("Filter by city name."),
    store: z3.string().optional().describe("Substring match on the store name or chain."),
    limit: z3.number().int().min(1).max(100).optional().describe("Max rows (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ food, city, store, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const nowIso = (/* @__PURE__ */ new Date()).toISOString();
    let q = supabaseForUser4(ctx).from("sale_observations").select("id,food_name,store_name,store_chain,city,sale_price_usd,regular_price_usd,savings_pct,starts_at,ends_at,pack_size,category").eq("moderation_status", "approved").lte("starts_at", nowIso).gte("ends_at", nowIso).order("savings_pct", { ascending: false, nullsFirst: false }).limit(limit ?? 25);
    if (food) q = q.ilike("food_name", `%${food}%`);
    if (city) q = q.ilike("city", `%${city}%`);
    if (store) q = q.or(`store_name.ilike.%${store}%,store_chain.ilike.%${store}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { deals: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-watchlist.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.0";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_watchlist_default = defineTool5({
  name: "list_watchlist",
  title: "List watchlist",
  description: "Return the foods the signed-in user is watching for deals, with their minimum-savings thresholds.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser5(ctx).from("watchlist_items").select("id,food_name,min_savings_pct,min_savings_usd,snoozed_until,updated_at").order("food_name", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
import { DEALS_FEATURE_ENABLED } from "npm:@/lib/featureFlags";
var projectRef = "paajifqvwmoqttefxykw";
var mcp_default = defineMcp({
  name: "saverspantry-mcp",
  title: "Saver's Pantry",
  version: "0.1.0",
  instructions: DEALS_FEATURE_ENABLED ? "Tools for Saver's Pantry \u2014 read and update the signed-in user's pantry, favorite stores, watchlist, and search current grocery deals. All data is scoped to the authenticated user." : "Tools for Saver's Pantry \u2014 read and update the signed-in user's pantry. All data is scoped to the authenticated user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  // v1.1: deals/stores tools return when DEALS_FEATURE_ENABLED is true.
  tools: DEALS_FEATURE_ENABLED ? [list_pantry_items_default, add_pantry_item_default, list_favorite_stores_default, search_deals_default, list_watchlist_default] : [list_pantry_items_default, add_pantry_item_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
